### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by thisfardi** [MRHRTZ/Quizizz-Cheat#1]
![image](https://github.com/MRHRTZ/Quizizz-Cheat/assets/38723240/2fcd5102-a392-436b-9e6d-084e3c647538)

**Comment by MRHRTZ** [comment]
This will not work if you have an admin session, for a workaround try using incognito mode or private mode browser, and don't log in to Quizizz.

I've tested your pin, and it's worked
![image](https://github.com/MRHRTZ/Quizizz-Cheat/assets/52845610/20f70e65-e98c-4dd8-b7d2-32d3ebbbb2e1)

**Comment by ThisMe124** [comment]
> This will not work if you have an admin session, for a workaround try using incognito mode or private mode browser, and don't log in to Quizizz.
> 
> I've tested your pin, and it's worked ![image](https://user-images.githubusercontent.com/52845610/272010347-20f70e65-e98c-4dd8-b7d2-32d3ebbbb2e1.png)

Umm this only get information metadata Like question not with answer? I am test only question but the answer not show

**Comment by MRHRTZ** [comment]
> Umm this only get information metadata Like question not with answer? I am test only question but the answer not show

For normal questions, all the answers will be immediately given
if the live questions, they will give the correct answers one by one in sequence and a bot with a random name will enter the question
but if the test question does not display the correct answer it only lists the answer (*just for now)

Closing issue.
